services:
  grafana:
    image: grafana/grafana:latest
    container_name: aptos-grafana
    restart: unless-stopped
    volumes:
      - grafana-volume:/var/lib/grafana:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    ports:
      - ${GRAFANA_SERVER_PORT:-3000}:3000
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: aptos-prometheus
    restart: unless-stopped
    entrypoint: /docker-entrypoint.sh
    ports:
      - ${PROM_SERVER_PORT:-9090}:9090
    volumes:
      - prometheus-volume:/prometheus:rw
      - ./prometheus/docker-entrypoin.sh:/docker-entrypoint.sh
      - ./prometheus/rules:/etc/prometheus/rules
    command:
      - --web.enable-lifecycle
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --storage.tsdb.retention.time=${PROM_RETENTION_TIME:-1w}
    environment:
      TESTNET_VALIDATOR_IP: ${TESTNET_VALIDATOR_IP}
      TESTNET_VALIDATOR_PORT: ${TESTNET_VALIDATOR_PORT}
      TESTNET_VFN_IP: ${TESTNET_VFN_IP}
      TESTNET_VFN_PORT: ${TESTNET_VFN_PORT}
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: aptos-alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager:/etc/alertmanager:ro
      - alertmanager-volume:/alertmanager:rw
    command:
      - --config.file=/etc/alertmanager/alertmanager.yaml
    networks:
      - monitor-net
    depends_on:
      - prometheus
    ports:
      - ${ALERTMANAGER_SERVER_PORT:-9093}:9093

volumes:
  grafana-volume:
    name: grafana-volume
  prometheus-volume:
    name: prometheus-volume
  alertmanager-volume:
    name: alertmanager-volume

networks:
  monitor-net:
    name: monitor-net
    driver: bridge

